# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2021 ImmortalWrt.org

name: Update Mirror

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  update-mirror:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        branch:
          - openwrt-18.06
          - openwrt-18.06-k5.4
          - openwrt-21.02
          - master
      fail-fast: false
      max-parallel: 2

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2

      - name: Init Compilation Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E apt-get -qq remove --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 coreutils gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf ecj fastjar re2c xz-utils tar
          for i in $(ls /usr/bin/*-8); do sudo -E ln -sf $i ${i%%-8*}; done 
          sudo -E ln -sf /usr/include/asm-generic /usr/include/asm
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo -E swapoff -a
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile

      - name: Checkout ImmortalWrt Source Tree on Branch ${{ matrix.branch }}
        uses: actions/checkout@v2
        with:
          repository: "immortalwrt/immortalwrt"
          ref: ${{ matrix.branch }}
          path: "immortalwrt"

      - name: Update Feeds
        run: |
          cd "immortalwrt"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Remove Download Mirrors
        run: sed -i -e "/unshift @mirrors/d" "immortalwrt/scripts/download.pl"

      - name: Download Packages
        run: |
          cd "immortalwrt"
          echo -e "CONFIG_ALL=y" > ".config"
          make defconfig
          make download -j128
          find dl -size -1024c -exec rm -f {} \;

      - name: Upload Files to CloudDrive
        env:
          BRANCH: ${{ matrix.branch }}
          SOURCE_PATH: "immortalwrt"
          UPLOADER_INFO: ${{ secrets.UPLOADER_INFO }}
          UPLOADER_CONF: "uploader.json"
        run: |
          mv "$SOURCE_PATH/dl" "$SOURCE_PATH/$BRANCH"
          echo -e "$UPLOADER_INFO" > "$UPLOADER_CONF"
          ./OneDriveUploader -f -c "$UPLOADER_CONF" -s "$SOURCE_PATH/$BRANCH" -r "immortalwrt/package-sources"

  cleanup-workflow-runs:
    runs-on: ubuntu-18.04
    needs: update-mirror
    steps:
      - name: Cleanup Workflow Runs
        uses: GitRML/delete-workflow-runs@v1.2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
